### ISSUE TITLE
Uncaught TypeError: Cannot read property 'animatableElement' of undefined

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/templating#525]
**I'm submitting a bug report**

* **Library Version:**
1.2.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.3

* **Node Version:**
6.9.1

* **NPM Version:**
4.0.3

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.27

* **Browser:**
Chrome 56.0.2924.87

* **Language:**
ESNext

**Current behavior:**

After cloning and npm install of the skeleton-esnext-webpack, I installed the aurelia-animator-css 1.0.1 plugin and got router views animated with `swap-order="after"` in `app.html`.

To switch to concurrent transitions, I modified the css and after switching the swap-order to "with", the `Cannot read property 'animatableElement' of undefined` error happens:

```css
@keyframes slideLeftIn {
  0% {
    -webkit-transform: translate3d(100%, 0, 0);
    transform: translate3d(100%, 0, 0);
  }
  100% {
    -webkit-transform: none;
    transform: none;
  }
}
@keyframes slideLeftOut {
  0% {
    -webkit-transform: none;
    transform: none;
  }
  100% {
    -webkit-transform: translate3d(-100%, 0, 0);
    transform: translate3d(-100%, 0, 0);
  }
}

section.au-enter-active {
  -webkit-animation: slideLeftIn 1s;
  animation: slideLeftIn 1s;
}
section.au-leave-active {
  -webkit-animation: slideLeftOut 1s;
  animation: slideLeftOut 1s;
}
```

Error log:

```shell
ERROR [app-router] TypeError: Cannot read property 'animatableElement' of undefined
    at getAnimatableElement (http://localhost:9000/aurelia.bundle.js:1587:11)
    at ViewSlot.animateView (http://localhost:9000/aurelia.bundle.js:1626:29)
    at ViewSlot.removeAt (http://localhost:9000/aurelia.bundle.js:1828:28)
    at _with (http://localhost:9000/aurelia.bundle.js:18465:36)
    at work (http://localhost:9000/aurelia.bundle.js:18572:7)
    at Array.forEach (native)
    at http://localhost:9000/aurelia.bundle.js:14623:18
From previous event:
    at NavigationInstruction._commitChanges (http://localhost:9000/aurelia.bundle.js:14622:31)
    at CommitChangesStep.run (http://localhost:9000/aurelia.bundle.js:14471:34)
    at next (http://localhost:9000/aurelia.bundle.js:14440:18)
    at next (http://localhost:9000/aurelia.bundle.js:14440:18)
From previous event:
    at LoadRouteStep.run (http://localhost:9000/aurelia.bundle.js:15697:66)
    at next (http://localhost:9000/aurelia.bundle.js:14440:18)
From previous event:
    at BuildNavigationPlanStep.run (http://localhost:9000/aurelia.bundle.js:14887:56)
    at next (http://localhost:9000/aurelia.bundle.js:14440:18)
    at http://localhost:9000/aurelia.bundle.js:16026:23
From previous event:
    at AppRouter.activate (http://localhost:9000/aurelia.bundle.js:15976:10)
    at http://localhost:9000/aurelia.bundle.js:15946:29
From previous event:
    at http://localhost:9000/aurelia.bundle.js:15945:22
    at http://localhost:9000/aurelia.bundle.js:15951:14
    at AppRouter.registerViewPort (http://localhost:9000/aurelia.bundle.js:15958:8)
    at new RouterView (http://localhost:9000/aurelia.bundle.js:18499:17)
    at Container.invoke (http://localhost:9000/aurelia.bundle.js:11786:23)
    at ProviderResolver.get (http://localhost:9000/aurelia.bundle.js:2029:72)
    at HtmlBehaviorResource.create (http://localhost:9000/aurelia.bundle.js:4037:56)
    at applyInstructions (http://localhost:9000/aurelia.bundle.js:2186:31)
    at ViewFactory.create (http://localhost:9000/aurelia.bundle.js:2407:7)
    at HtmlBehaviorResource.create (http://localhost:9000/aurelia.bundle.js:4049:39)
From previous event:
    at CompositionEngine._createControllerAndSwap (http://localhost:9000/aurelia.bundle.js:4436:17)
    at Aurelia.setRoot (http://localhost:9000/aurelia.bundle.js:13052:19)
    at Object._callee$ (http://localhost:9000/app.bundle.js:22165:21)
    at tryCatch (http://localhost:9000/aurelia-bootstrap.bundle.js:1090:40)
    at Generator.invoke [as _invoke] (http://localhost:9000/aurelia-bootstrap.bundle.js:1381:22)
    at step (http://localhost:9000/app.bundle.js:22134:191)
    at http://localhost:9000/app.bundle.js:22134:361
From previous event:
    at Object.<anonymous> (http://localhost:9000/app.bundle.js:22134:99)
From previous event:
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15717:9
From previous event:
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15714:44
From previous event:
    at Object.<anonymous> (http://localhost:9000/aurelia-bootstrap.bundle.js:15736:1)
    at Object.aurelia-bootstrapper-webpack (http://localhost:9000/aurelia-bootstrap.bundle.js:15737:30)
    at __webpack_require__ (http://localhost:9000/aurelia-bootstrap.bundle.js:57:38)
    at Object.423 (http://localhost:9000/aurelia-bootstrap.bundle.js:14228:1)
    at __webpack_require__ (http://localhost:9000/aurelia-bootstrap.bundle.js:57:38)
    at 10 (http://localhost:9000/aurelia-bootstrap.bundle.js:140:18)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:143:10
```

The error happens on opening the initial view and repeated on each route change.

* **What is the expected behavior?**

According to [issue#470](https://github.com/aurelia/templating/issues/470) the error should not happen, perhaps this basic example helps finding the cause.
